# This workflow should be added to the elastic/security repository
# File: .github/workflows/eck-cve-triage.yml
#
# It triggers when issues are created or labeled with "ECK" label
# and automatically performs CVE triage analysis.

name: ECK CVE Triage

on:
  issues:
    types: [opened, labeled]

# Limit permissions to minimum required
permissions:
  issues: write
  contents: read

jobs:
  triage:
    # Only run if the issue has the ECK label
    if: contains(github.event.issue.labels.*.name, 'ECK')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout ECK repository
        uses: actions/checkout@v4
        with:
          repository: elastic/cloud-on-k8s
          ref: main
          # If the ECK repo is private, you'll need a PAT with repo access
          # token: ${{ secrets.ECK_REPO_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: hack/cve-triage/go.sum

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Build CVE Triage Tool
        run: |
          cd hack/cve-triage
          go build -o cve-triage .

      - name: Run CVE Triage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          cd hack/cve-triage
          ./cve-triage \
            --issue-number=${{ github.event.issue.number }} \
            --issue-title="${{ github.event.issue.title }}" \
            --issue-body="${{ github.event.issue.body }}" \
            --owner=${{ github.repository_owner }} \
            --repo=${{ github.event.repository.name }} \
            --go-mod=../../go.mod \
            --add-labels

      - name: Report Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '⚠️ CVE triage automation failed. Please triage manually.\n\nSee [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
            })

